- hosts: all
  tasks:
  - name: copying jdk
    copy:
     src: "/root/jdk-8u171-linux-x64.rpm"
     dest: "/root/"

  - name: copying hadoop
    copy:
     src: "/root/hadoop-1.2.1-1.x86_64.rpm"
     dest: "/root/"

  - name: installing jdk
    command: "rpm -ivh /root/jdk-8u171-linux-x64.rpm --force"

  - name: installing hadoop
    command: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm --force"
  

- hosts: master
  vars:
  - port_no: 9001
  - master_dir: "/root/nn"

  tasks:
  - name: configuring hdfs-site.xml file
    template:
      src: "/root/master/hdfs-site.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

  - name: configuring core-site.xml file
    template:
      src: "/root/master/core-site.xml"
      dest: "/etc/hadoop/core-site.xml"

  - name: create directory
    file: 
      path: "{{master_dir}}"
      state: directory
  
  - name: formatting the namenode directory
    shell: "hadoop namenode -format"

  - name: enabling firewall for port
    firewalld:
      port: "{{port_no}}"
      permanent: yes
      state: enabled

  - name: starting master service
    service:
      name: "hadoop-namenode.service"
      state: started

- hosts: slave
  vars:
  - slave_dir: "/root/dn"
  - master_ip: "192.168.1.38"
  - port_no: 9001
  tasks:
  - name: configuring hdfs-site.xml file
    template:
      src: "/root/slave/hdfs-site.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

  - name: configuring core-site.xml file
    template:
      src: "/root/slave/core-site.xml"
      dest: "/etc/hadoop/core-site.xml"

  - name: creating slave directory
    file:
      path: "{{slave_dir}}"
      state: directory

  - name: starting slave service
    service:
      name: "hadoop-datanode.service"
      state: started



